<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
  vagrant_memsize = ENV['BEAKER_VAGRANT_MEMSIZE'] ? ENV['BEAKER_VAGRANT_MEMSIZE'] : 256
-%>
HOSTS:
  el7:
    roles:
      - default
      - el7
    platform: el-7-x86_64
    box: centos/7
    hypervisor: <%= hypervisor %>

  el8:
    roles:
      - el8
    platform: el-8-x86_64
    box: generic/centos8
    hypervisor: <%= hypervisor %>

CONFIG:
  log_level: verbose
  type: aio
  # Pinning the puppet agent version to 7.12 because 7.13.1 introduced a breaking change
  # to searching for hieradata
  puppet_agent_version: <%= ENV['PUPPET_VERSION'] || '7.12.*' %>
  vagrant_memsize: <%= vagrant_memsize %>
<% if ENV['BEAKER_PUPPET_COLLECTION'] -%>
  puppet_collection: <%= ENV['BEAKER_PUPPET_COLLECTION'] %>
<% end -%>
